### ISSUE TITLE
Incorrect textsize in Recycle View on multi-entries

### ISSUE THREAD

**Issue by NRais** [isaacy2012/IDScanner#6]
When you put in more than one entry sometimes the text resizes. Particularly for large entries:
![image](https://user-images.githubusercontent.com/61948142/125269978-573cd400-e35d-11eb-9bd4-be4e7c7dc901.png)

A) This can have a trickle down effect, making subsequent entries smaller when they shouldn't be:

![image](https://user-images.githubusercontent.com/61948142/125270138-7b98b080-e35d-11eb-856f-b8eaa5f96d14.png)

B) This can follow on to later instances of the Recycle View even after everything is deleted:

![image](https://user-images.githubusercontent.com/61948142/125270518-d7fbd000-e35d-11eb-830b-ef53975ef00d.png)

**Comment by isaacy2012** [comment]
Fixed as of `4a3395d`
